enum itch5x_msg_type : bits(8), endian(little) {
    ITCH5x_MT_SYSTEM_EVENT_MESSAGE      = 'S',
    ITCH5x_MT_STOCK_DIRECTORY           = 'R',
    ITCH5x_MT_STOCK_TRADING_ACTION      = 'H',
    ITCH5x_MT_REG_SHO_INDICATOR         = 'Y',
    ITCH5x_MT_MKT_PARTICIPANT_POSITION  = 'L',
    ITCH5x_MT_MWCB_LEVEL_DECLINE        = 'V',
    ITCH5x_MT_MWCB_STATUS               = 'W',
    ITCH5x_MT_IPO_QUOTING_PERIOD_UPDATE = 'K',
    ITCH5x_MT_ADD_ORDER                 = 'A',
    ITCH5x_MT_ADD_ORDER_ATTRIBUTED      = 'F',
    ITCH5x_MT_ORDER_EXECUTED            = 'E',
    ITCH5x_MT_ORDER_EXECUTED_WITH_PRICE = 'C',
    ITCH5x_MT_ORDER_CANCEL              = 'X',
    ITCH5x_MT_ORDER_DELETE              = 'D',
    ITCH5x_MT_ORDER_REPLACE             = 'U',
    ITCH5x_MT_TRADE                     = 'P',
    ITCH5x_MT_CROSS_TRADE               = 'Q',
    ITCH5x_MT_BROKEN_TRADE              = 'B',
    ITCH5x_MT_NOII                      = 'I',
    ITCH5x_MT_RPII                      = 'N',
}

struct itch_msg_header
    : bytes(11)
    , endian(little)
{
    itch_msg_type message_type;
    u16           stock_locate;
    u16           tracking_number;
    timestamp     timestamp;
}

struct itch_system_event : bytes(12) {
    itch_msg_type message_type;
    u16           stock_locate;
    u16           tracking_number;
    timestamp     timestamp;
    c8            event_code;
}

