enum itch5x_message_type {
    ITCH5X_MT_SYSTEM_EVENT             = 'S',
    ITCH5X_MT_STOCK_DIRECTORY          = 'R',
    ITCH5X_MT_STOCK_TRADING_ACTION     = 'H',
    ITCH5X_MT_REG_SHO_RESTRICTED_IND   = 'Y',
    ITCH5X_MT_MKT_PARTICIPANT_POSITION = 'L',
    ITCH5X_MT_MWCB_DECLINE_LEVEL       = 'V',
    ITCH5X_MT_MWCB_STATUS              = 'W',
    ITCH5X_MT_IPO_QUOTING_UPDATE       = 'K',
    ITCH5X_MT_ADD_ORDER                = 'A',
    ITCH5X_MT_ADD_ORDER_ATTRIB         = 'F',
    ITCH5X_MT_ORDER_EXECUTED           = 'E',
    ITCH5X_MT_ORDER_EXECUTED_PRICE     = 'C',
    ITCH5X_MT_ORDER_CANCEL             = 'X',
    ITCH5X_MT_ORDER_DELETE             = 'D',
    ITCH5X_MT_ORDER_REPLACE            = 'U',
    ITCH5X_MT_TRADE                    = 'P',
    ITCH5X_MT_CROSS_TRADE              = 'Q',
    ITCH5X_MT_BROKEN_TRADE             = 'B',
    ITCH5X_MT_NOII                     = 'I',
    ITCH5X_MT_RPII                     = 'N',
}

enum itch5x_side {
    ITCH5X_SIDE_BUY  = 'B',
    ITCH5X_SIDE_SELL = 'S',
}

struct itch5x_add_order [bytes=36] {
    u8    message_type;
    u16   stock_locate;
    u16   tracking_number;
    u48   timestamp;
    u64   order_reference_number;
    u8    side;
    u32   shares;
    u8[8] stock;
    u32   price;
}

struct itch5x_add_order_attrib [bytes=40] {
    u8    message_type;
    u16   stock_locate;
    u16   tracking_number;
    u48   timestamp;
    u64   order_reference_number;
    u8    side;
    u32   shares;
    u8[8] stock;
    u32   price;
    u8[4] mpid;
}

struct itch5x_order_executed [bytes=31] {
    u8  message_type;
    u16 stock_locate;
    u16 tracking_number;
    u48 timestamp;
    u64 order_reference_number;
    u32 executed_shares;
    u64 match_number;
}

struct itch5x_order_executed_price [bytes=36] {
    u8  message_type;
    u16 stock_locate;
    u16 tracking_number;
    u48 timestamp;
    u64 order_reference_number;
    u32 executed_shares;
    u64 match_number;
    u8  printable;
    u32 execution_price;
}

struct itch5x_order_cancel [bytes=23] {
    u8  message_type;
    u16 stock_locate;
    u16 tracking_number;
    u48 timestamp;
    u64 order_reference_number;
    u32 canceled_shares;
}

struct itch5x_order_delete [bytes=19] {
    u8  message_type;
    u16 stock_locate;
    u16 tracking_number;
    u48 timestamp;
    u64 order_reference_number;
}

struct itch5x_order_replace [bytes=35] {
    u8  message_type;
    u16 stock_locate;
    u16 tracking_number;
    u48 timestamp;
    u64 orig_order_reference_number;
    u64 new_order_reference_number;
    u32 shares;
    u32 price;
}

struct itch5x_trade [bytes=44] {
    u8    message_type;
    u16   stock_locate;
    u16   tracking_number;
    u48   timestamp;
    u64   order_reference_number;
    u8    unused;
    u32   shares;
    u8[8] stock;
    u32   price;
    u64   match_number;
}

struct itch5x_cross_trade [bytes=40] {
    u8    message_type;
    u16   stock_locate;
    u16   tracking_number;
    u48   timestamp;
    u64   shares;
    u8[8] stock;
    u32   cross_price;
    u64   match_number;
    u8    cross_type;
}

struct itch5x_noii [bytes=50] {
    u8    message_type;
    u16   stock_locate;
    u16   tracking_number;
    u48   timestamp;
    u64   paired_shares;
    u64   imbalance_shares;
    u8    imbalance_direction;
    u8[8] stock;
    u32   far_price;
    u32   near_price;
    u32   reference_price;
    u8    cross_type;
    u8    price_variation_ind;
}

